version: '3.9'

services:
  mssql:
    container_name: mssql
    image: mcr.microsoft.com/azure-sql-edge:latest
    user: root
    ports:
      - 1433:1433
    environment:
      MSSQL_SA_PASSWORD: 6ha9hqOpaJI430J*JVr*
      ACCEPT_EULA: Y
    restart: unless-stopped
    volumes:
      - sqlserver_data:/var/opt/mssql

  mssql-tools:
    container_name: tools
    image: mcr.microsoft.com/mssql-tools:latest
    user: root
    depends_on:
      - mssql
    environment:
      MSSQL_SA_PASSWORD: 6ha9hqOpaJI430J*JVr*
      MSSQL_HOST: mssql
      MSSQL_PORT: 1433
    command: bash /opt/scripts/configure.sh
    volumes:
      - ../src/Template.Infrastructure/Data/scripts:/opt/scripts:ro
    healthcheck:
      test: "exit 0"
      interval: 30s
      timeout: 10s
      retries: 5
    
  api:
    container_name: api
    build:
      context: ../
      dockerfile: ./src/Template.Api/Dockerfile.debug
    restart: unless-stopped
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 8000:80
    command: [
      "dotnet", 
      "watch", 
      "run", 
      -v,
      "--project", 
      "/app/src/Template.Api/Template.Api.csproj", 
      "--urls", 
      "http://*:80",
      "--non-interactive"
      ]
    depends_on:
      mssql-tools:
        condition: service_completed_successfully
    volumes:
      - ../:/app
      - /app/src/Template.Api/obj/
      - /app/src/Template.Api/bin/
      - /app/src/Template.Domain/obj/
      - /app/src/Template.Domain/bin/
      - /app/src/Template.Infrastructure/obj/
      - /app/src/Template.Infrastructure/bin/
      - /app/src/Template.Application/obj/
      - /app/src/Template.Application/bin/

volumes:
  sqlserver_data: